name: 'Run eslint with reviewdog'
description: '🐶 Run eslint and tslint with reviewdog on pull requests to improve code review experience.'
author: 'haya14busa (reviewdog)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-check'
  lint_dirs:
    description: "Directories to lint. Default: '.'"
    default: '.'
  lint_ext:
    decription: "Eslint `--ext` flag. Defaults: .js,.jsx,.ts,.tsx"
    default: '.js,.ts,.tsx'
  tslint:
    description: "Use tslint instead"
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'alert-octagon'
  color: 'blue'
